/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[4] = {0, 0, 0, 0};
static const casadi_int casadi_s1[7] = {1, 2, 0, 1, 2, 0, 0};
static const casadi_int casadi_s2[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s3[6] = {1, 2, 0, 1, 1, 0};
static const casadi_int casadi_s4[5] = {2, 1, 0, 1, 0};
static const casadi_int casadi_s5[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s6[5] = {0, 1, 4, 5, 8};
static const casadi_int casadi_s7[6] = {1, 2, 0, 0, 1, 0};
static const casadi_int casadi_s8[5] = {2, 1, 0, 1, 1};
static const casadi_int casadi_s9[20] = {8, 8, 0, 2, 4, 6, 8, 9, 9, 9, 9, 0, 1, 0, 1, 2, 3, 2, 3, 4};
static const casadi_int casadi_s10[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s11[3] = {0, 0, 0};
static const casadi_int casadi_s12[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s13[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s14[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s15[11] = {0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[4] = {1., 0., 0., 1.};
static const casadi_real casadi_c1[4] = {5., 0., 0., 5.};
static const casadi_real casadi_c2[4] = {1.0000000000000000e-02, 0., 0., 5.0000000000000001e-03};

/* Drone_ode_cost_ext_cost_fun_jac_hess:(i0[6],i1[2],i2[],i3[13])->(o0,o1[8],o2[8x8,9nz],o3[],o4[0x8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, w2, *w3=w+5, *w4=w+7, *w5=w+9, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+27, *w21=w+40, *w22=w+42, *w23=w+44, *w24=w+48, *w25=w+54, *w26=w+56, *w27=w+58, *w28=w+62, *w29=w+64, *w30=w+66, *w31=w+70, *w32=w+74, *w33=w+78, *w34=w+82, *w35=w+86, *w37=w+95, *w38=w+103, *w39=w+108;
  /* #0: @0 = 1.5 */
  w0 = 1.5000000000000000e+00;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = sq(@1) */
  w2 = casadi_sq( w1 );
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @2 = 0 */
  w2 = 0.;
  /* #5: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #6: @4 = zeros(2x1) */
  casadi_clear(w4, 2);
  /* #7: @5 = 
  [[1, 0], 
   [0, 1]] */
  casadi_copy(casadi_c0, 4, w5);
  /* #8: @6 = 0 */
  w6 = 0.;
  /* #9: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #10: @8 = input[3][1] */
  w8 = arg[3] ? arg[3][1] : 0;
  /* #11: @9 = input[3][2] */
  w9 = arg[3] ? arg[3][2] : 0;
  /* #12: @10 = input[3][3] */
  w10 = arg[3] ? arg[3][3] : 0;
  /* #13: @11 = input[3][4] */
  w11 = arg[3] ? arg[3][4] : 0;
  /* #14: @12 = input[3][5] */
  w12 = arg[3] ? arg[3][5] : 0;
  /* #15: @13 = input[3][6] */
  w13 = arg[3] ? arg[3][6] : 0;
  /* #16: @14 = input[3][7] */
  w14 = arg[3] ? arg[3][7] : 0;
  /* #17: @15 = input[3][8] */
  w15 = arg[3] ? arg[3][8] : 0;
  /* #18: @16 = input[3][9] */
  w16 = arg[3] ? arg[3][9] : 0;
  /* #19: @17 = input[3][10] */
  w17 = arg[3] ? arg[3][10] : 0;
  /* #20: @18 = input[3][11] */
  w18 = arg[3] ? arg[3][11] : 0;
  /* #21: @19 = input[3][12] */
  w19 = arg[3] ? arg[3][12] : 0;
  /* #22: @20 = vertcat(@7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w20;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #23: @21 = @20[3:5] */
  for (rr=w21, ss=w20+3; ss!=w20+5; ss+=1) *rr++ = *ss;
  /* #24: @22 = @21' */
  casadi_copy(w21, 2, w22);
  /* #25: @6 = mac(@22,@21,@6) */
  for (i=0, rr=(&w6); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w21+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #26: @23 = @6[0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w23, ss=(&w6); cii!=casadi_s0+4; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #27: @5 = (@5-@23) */
  for (i=0, rr=w5, cs=w23; i<4; ++i) (*rr++) -= (*cs++);
  /* #28: @22 = @20[:2] */
  for (rr=w22, ss=w20+0; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #29: @6 = input[0][0] */
  w6 = arg[0] ? arg[0][0] : 0;
  /* #30: @7 = input[0][1] */
  w7 = arg[0] ? arg[0][1] : 0;
  /* #31: @8 = input[0][3] */
  w8 = arg[0] ? arg[0][3] : 0;
  /* #32: @9 = input[0][4] */
  w9 = arg[0] ? arg[0][4] : 0;
  /* #33: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #34: @24 = vertcat(@6, @7, @1, @8, @9, @10) */
  rr=w24;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w1;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #35: @25 = @24[:2] */
  for (rr=w25, ss=w24+0; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #36: @22 = (@22-@25) */
  for (i=0, rr=w22, cs=w25; i<2; ++i) (*rr++) -= (*cs++);
  /* #37: @4 = mac(@5,@22,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w5+j, tt=w22+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #38: @25 = @4' */
  casadi_copy(w4, 2, w25);
  /* #39: @23 = 
  [[5, 0], 
   [0, 5]] */
  casadi_copy(casadi_c1, 4, w23);
  /* #40: @3 = mac(@25,@23,@3) */
  for (i=0, rr=w3; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #41: @2 = mac(@3,@4,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #42: @6 = 0 */
  w6 = 0.;
  /* #43: @25 = zeros(1x2) */
  casadi_clear(w25, 2);
  /* #44: @7 = dot(@21, @22) */
  w7 = casadi_dot(2, w21, w22);
  /* #45: @22 = (@7*@21) */
  for (i=0, rr=w22, cs=w21; i<2; ++i) (*rr++)  = (w7*(*cs++));
  /* #46: @26 = @22' */
  casadi_copy(w22, 2, w26);
  /* #47: @27 = 
  [[5, 0], 
   [0, 5]] */
  casadi_copy(casadi_c1, 4, w27);
  /* #48: @25 = mac(@26,@27,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #49: @6 = mac(@25,@22,@6) */
  for (i=0, rr=(&w6); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w22+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #50: @2 = (@2+@6) */
  w2 += w6;
  /* #51: @0 = (@0+@2) */
  w0 += w2;
  /* #52: @2 = 0.2 */
  w2 = 2.0000000000000001e-01;
  /* #53: @26 = @24[3:5] */
  for (rr=w26, ss=w24+3; ss!=w24+5; ss+=1) *rr++ = *ss;
  /* #54: @6 = dot(@21, @26) */
  w6 = casadi_dot(2, w21, w26);
  /* #55: @2 = (@2*@6) */
  w2 *= w6;
  /* #56: @0 = (@0-@2) */
  w0 -= w2;
  /* #57: @2 = 0 */
  w2 = 0.;
  /* #58: @26 = zeros(1x2) */
  casadi_clear(w26, 2);
  /* #59: @6 = input[1][0] */
  w6 = arg[1] ? arg[1][0] : 0;
  /* #60: @7 = input[1][1] */
  w7 = arg[1] ? arg[1][1] : 0;
  /* #61: @28 = vertcat(@6, @7) */
  rr=w28;
  *rr++ = w6;
  *rr++ = w7;
  /* #62: @29 = @28' */
  casadi_copy(w28, 2, w29);
  /* #63: @30 = 
  [[0.01, 0], 
   [0, 0.005]] */
  casadi_copy(casadi_c2, 4, w30);
  /* #64: @26 = mac(@29,@30,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w29+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #65: @2 = mac(@26,@28,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w28+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #66: @0 = (@0+@2) */
  w0 += w2;
  /* #67: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #68: @26 = @26' */
  /* #69: @29 = zeros(1x2) */
  casadi_clear(w29, 2);
  /* #70: @28 = @28' */
  /* #71: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #72: @29 = mac(@28,@31,@29) */
  for (i=0, rr=w29; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w31+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #73: @29 = @29' */
  /* #74: @26 = (@26+@29) */
  for (i=0, rr=w26, cs=w29; i<2; ++i) (*rr++) += (*cs++);
  /* #75: {@0, @2} = vertsplit(@26) */
  w0 = w26[0];
  w2 = w26[1];
  /* #76: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #77: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #78: @24 = zeros(6x1) */
  casadi_clear(w24, 6);
  /* #79: @2 = -0.2 */
  w2 = -2.0000000000000001e-01;
  /* #80: @26 = (@2*@21) */
  for (i=0, rr=w26, cs=w21; i<2; ++i) (*rr++)  = (w2*(*cs++));
  /* #81: (@24[3:5] += @26) */
  for (rr=w24+3, ss=w26; rr!=w24+5; rr+=1) *rr += *ss++;
  /* #82: @25 = @25' */
  /* #83: @26 = zeros(1x2) */
  casadi_clear(w26, 2);
  /* #84: @22 = @22' */
  /* #85: @32 = @27' */
  for (i=0, rr=w32, cs=w27; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #86: @26 = mac(@22,@32,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w32+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #87: @26 = @26' */
  /* #88: @25 = (@25+@26) */
  for (i=0, rr=w25, cs=w26; i<2; ++i) (*rr++) += (*cs++);
  /* #89: @2 = dot(@21, @25) */
  w2 = casadi_dot(2, w21, w25);
  /* #90: @25 = (@2*@21) */
  for (i=0, rr=w25, cs=w21; i<2; ++i) (*rr++)  = (w2*(*cs++));
  /* #91: @26 = zeros(2x1) */
  casadi_clear(w26, 2);
  /* #92: @33 = @5' */
  for (i=0, rr=w33, cs=w5; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #93: @3 = @3' */
  /* #94: @22 = zeros(1x2) */
  casadi_clear(w22, 2);
  /* #95: @4 = @4' */
  /* #96: @34 = @23' */
  for (i=0, rr=w34, cs=w23; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #97: @22 = mac(@4,@34,@22) */
  for (i=0, rr=w22; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w4+j, tt=w34+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #98: @22 = @22' */
  /* #99: @3 = (@3+@22) */
  for (i=0, rr=w3, cs=w22; i<2; ++i) (*rr++) += (*cs++);
  /* #100: @26 = mac(@33,@3,@26) */
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w33+j, tt=w3+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #101: @25 = (@25+@26) */
  for (i=0, rr=w25, cs=w26; i<2; ++i) (*rr++) += (*cs++);
  /* #102: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<2; ++i) *rr++ = (- *cs++ );
  /* #103: (@24[:2] += @25) */
  for (rr=w24+0, ss=w25; rr!=w24+2; rr+=1) *rr += *ss++;
  /* #104: {@2, @0, @6, @7, @8, @9} = vertsplit(@24) */
  w2 = w24[0];
  w0 = w24[1];
  w6 = w24[2];
  w7 = w24[3];
  w8 = w24[4];
  w9 = w24[5];
  /* #105: output[1][2] = @2 */
  if (res[1]) res[1][2] = w2;
  /* #106: output[1][3] = @0 */
  if (res[1]) res[1][3] = w0;
  /* #107: @0 = 1.5 */
  w0 = 1.5000000000000000e+00;
  /* #108: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #109: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #110: @6 = (@6+@1) */
  w6 += w1;
  /* #111: output[1][4] = @6 */
  if (res[1]) res[1][4] = w6;
  /* #112: output[1][5] = @7 */
  if (res[1]) res[1][5] = w7;
  /* #113: output[1][6] = @8 */
  if (res[1]) res[1][6] = w8;
  /* #114: output[1][7] = @9 */
  if (res[1]) res[1][7] = w9;
  /* #115: @35 = zeros(8x8,9nz) */
  casadi_clear(w35, 9);
  /* #116: @25 = zeros(1x2) */
  casadi_clear(w25, 2);
  /* #117: @24 = ones(8x1,6nz) */
  casadi_fill(w24, 6, 1.);
  /* #118: {@9, NULL, @8, NULL, @7, NULL, NULL, NULL} = vertsplit(@24) */
  w9 = w24[0];
  w8 = w24[1];
  w7 = w24[2];
  /* #119: @36 = 00 */
  /* #120: @6 = vertcat(@9, @36) */
  rr=(&w6);
  *rr++ = w9;
  /* #121: @9 = @6' */
  casadi_copy((&w6), 1, (&w9));
  /* #122: @25 = mac(@9,@30,@25) */
  casadi_mtimes((&w9), casadi_s3, w30, casadi_s2, w25, casadi_s1, w, 0);
  /* #123: @25 = @25' */
  /* #124: @26 = zeros(1x2) */
  casadi_clear(w26, 2);
  /* #125: @6 = @6' */
  /* #126: @26 = mac(@6,@31,@26) */
  casadi_mtimes((&w6), casadi_s3, w31, casadi_s2, w26, casadi_s1, w, 0);
  /* #127: @26 = @26' */
  /* #128: @25 = (@25+@26) */
  for (i=0, rr=w25, cs=w26; i<2; ++i) (*rr++) += (*cs++);
  /* #129: {@6, @9} = vertsplit(@25) */
  w6 = w25[0];
  w9 = w25[1];
  /* #130: @24 = zeros(6x1) */
  casadi_clear(w24, 6);
  /* #131: @25 = zeros(1x2) */
  casadi_clear(w25, 2);
  /* #132: @1 = project(@21) */
  casadi_sparsify(w21, (&w1), casadi_s4, 0);
  /* #133: @2 = @8[0] */
  for (rr=(&w2), ss=(&w8)+0; ss!=(&w8)+1; ss+=1) *rr++ = *ss;
  /* #134: @2 = (-@2) */
  w2 = (- w2 );
  /* #135: @8 = dot(@1, @2) */
  w8 = casadi_dot(1, (&w1), (&w2));
  /* #136: @26 = (@21*@8) */
  for (i=0, rr=w26, cr=w21; i<2; ++i) (*rr++)  = ((*cr++)*w8);
  /* #137: @3 = @26' */
  casadi_copy(w26, 2, w3);
  /* #138: @25 = mac(@3,@27,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w27+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #139: @25 = @25' */
  /* #140: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #141: @26 = @26' */
  /* #142: @3 = mac(@26,@32,@3) */
  for (i=0, rr=w3; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w32+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #143: @3 = @3' */
  /* #144: @25 = (@25+@3) */
  for (i=0, rr=w25, cs=w3; i<2; ++i) (*rr++) += (*cs++);
  /* #145: @8 = dot(@21, @25) */
  w8 = casadi_dot(2, w21, w25);
  /* #146: @25 = (@21*@8) */
  for (i=0, rr=w25, cr=w21; i<2; ++i) (*rr++)  = ((*cr++)*w8);
  /* #147: @3 = zeros(2x1) */
  casadi_clear(w3, 2);
  /* #148: @26 = zeros(1x2) */
  casadi_clear(w26, 2);
  /* #149: @22 = zeros(2x1) */
  casadi_clear(w22, 2);
  /* #150: @22 = mac(@5,@2,@22) */
  casadi_mtimes(w5, casadi_s2, (&w2), casadi_s4, w22, casadi_s5, w, 0);
  /* #151: @4 = @22' */
  casadi_copy(w22, 2, w4);
  /* #152: @26 = mac(@4,@23,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w4+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #153: @26 = @26' */
  /* #154: @4 = zeros(1x2) */
  casadi_clear(w4, 2);
  /* #155: @22 = @22' */
  /* #156: @4 = mac(@22,@34,@4) */
  for (i=0, rr=w4; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w34+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #157: @4 = @4' */
  /* #158: @26 = (@26+@4) */
  for (i=0, rr=w26, cs=w4; i<2; ++i) (*rr++) += (*cs++);
  /* #159: @3 = mac(@33,@26,@3) */
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w33+j, tt=w26+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #160: @25 = (@25+@3) */
  for (i=0, rr=w25, cs=w3; i<2; ++i) (*rr++) += (*cs++);
  /* #161: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<2; ++i) *rr++ = (- *cs++ );
  /* #162: (@24[:2] += @25) */
  for (rr=w24+0, ss=w25; rr!=w24+2; rr+=1) *rr += *ss++;
  /* #163: {@2, @8, @1, @10, @11, @12} = vertsplit(@24) */
  w2 = w24[0];
  w8 = w24[1];
  w1 = w24[2];
  w10 = w24[3];
  w11 = w24[4];
  w12 = w24[5];
  /* #164: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #165: @0 = (@0*@7) */
  w0 *= w7;
  /* #166: @1 = (@1+@0) */
  w1 += w0;
  /* #167: @37 = vertcat(@6, @9, @2, @8, @1, @10, @11, @12) */
  rr=w37;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w1;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #168: @38 = @37[:5] */
  for (rr=w38, ss=w37+0; ss!=w37+5; ss+=1) *rr++ = *ss;
  /* #169: (@35[0, 1, 4, 5, 8] = @38) */
  for (cii=casadi_s6, rr=w35, ss=w38; cii!=casadi_s6+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #170: @38 = @37[:5] */
  for (rr=w38, ss=w37+0; ss!=w37+5; ss+=1) *rr++ = *ss;
  /* #171: (@35[:10:2] = @38) */
  for (rr=w35+0, ss=w38; rr!=w35+10; rr+=2) *rr = *ss++;
  /* #172: @25 = zeros(1x2) */
  casadi_clear(w25, 2);
  /* #173: @36 = 00 */
  /* #174: @3 = ones(8x1,2nz) */
  casadi_fill(w3, 2, 1.);
  /* #175: {NULL, @6, NULL, @9, NULL, NULL, NULL, NULL} = vertsplit(@3) */
  w6 = w3[0];
  w9 = w3[1];
  /* #176: @2 = vertcat(@36, @6) */
  rr=(&w2);
  *rr++ = w6;
  /* #177: @6 = @2' */
  casadi_copy((&w2), 1, (&w6));
  /* #178: @25 = mac(@6,@30,@25) */
  casadi_mtimes((&w6), casadi_s7, w30, casadi_s2, w25, casadi_s1, w, 0);
  /* #179: @25 = @25' */
  /* #180: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #181: @2 = @2' */
  /* #182: @3 = mac(@2,@31,@3) */
  casadi_mtimes((&w2), casadi_s7, w31, casadi_s2, w3, casadi_s1, w, 0);
  /* #183: @3 = @3' */
  /* #184: @25 = (@25+@3) */
  for (i=0, rr=w25, cs=w3; i<2; ++i) (*rr++) += (*cs++);
  /* #185: {@2, @6} = vertsplit(@25) */
  w2 = w25[0];
  w6 = w25[1];
  /* #186: @24 = zeros(6x1) */
  casadi_clear(w24, 6);
  /* #187: @25 = zeros(1x2) */
  casadi_clear(w25, 2);
  /* #188: @8 = project(@21) */
  casadi_sparsify(w21, (&w8), casadi_s8, 0);
  /* #189: @1 = @9[0] */
  for (rr=(&w1), ss=(&w9)+0; ss!=(&w9)+1; ss+=1) *rr++ = *ss;
  /* #190: @1 = (-@1) */
  w1 = (- w1 );
  /* #191: @9 = dot(@8, @1) */
  w9 = casadi_dot(1, (&w8), (&w1));
  /* #192: @3 = (@21*@9) */
  for (i=0, rr=w3, cr=w21; i<2; ++i) (*rr++)  = ((*cr++)*w9);
  /* #193: @26 = @3' */
  casadi_copy(w3, 2, w26);
  /* #194: @25 = mac(@26,@27,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #195: @25 = @25' */
  /* #196: @26 = zeros(1x2) */
  casadi_clear(w26, 2);
  /* #197: @3 = @3' */
  /* #198: @26 = mac(@3,@32,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w32+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #199: @26 = @26' */
  /* #200: @25 = (@25+@26) */
  for (i=0, rr=w25, cs=w26; i<2; ++i) (*rr++) += (*cs++);
  /* #201: @9 = dot(@21, @25) */
  w9 = casadi_dot(2, w21, w25);
  /* #202: @21 = (@21*@9) */
  for (i=0, rr=w21; i<2; ++i) (*rr++) *= w9;
  /* #203: @25 = zeros(2x1) */
  casadi_clear(w25, 2);
  /* #204: @26 = zeros(1x2) */
  casadi_clear(w26, 2);
  /* #205: @3 = zeros(2x1) */
  casadi_clear(w3, 2);
  /* #206: @3 = mac(@5,@1,@3) */
  casadi_mtimes(w5, casadi_s2, (&w1), casadi_s8, w3, casadi_s5, w, 0);
  /* #207: @4 = @3' */
  casadi_copy(w3, 2, w4);
  /* #208: @26 = mac(@4,@23,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w4+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #209: @26 = @26' */
  /* #210: @4 = zeros(1x2) */
  casadi_clear(w4, 2);
  /* #211: @3 = @3' */
  /* #212: @4 = mac(@3,@34,@4) */
  for (i=0, rr=w4; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w34+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #213: @4 = @4' */
  /* #214: @26 = (@26+@4) */
  for (i=0, rr=w26, cs=w4; i<2; ++i) (*rr++) += (*cs++);
  /* #215: @25 = mac(@33,@26,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w33+j, tt=w26+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #216: @21 = (@21+@25) */
  for (i=0, rr=w21, cs=w25; i<2; ++i) (*rr++) += (*cs++);
  /* #217: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) *rr++ = (- *cs++ );
  /* #218: (@24[:2] += @21) */
  for (rr=w24+0, ss=w21; rr!=w24+2; rr+=1) *rr += *ss++;
  /* #219: {@1, @9, @8, @10, @11, @12} = vertsplit(@24) */
  w1 = w24[0];
  w9 = w24[1];
  w8 = w24[2];
  w10 = w24[3];
  w11 = w24[4];
  w12 = w24[5];
  /* #220: @37 = vertcat(@2, @6, @1, @9, @8, @10, @11, @12) */
  rr=w37;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #221: @33 = @37[:4] */
  for (rr=w33, ss=w37+0; ss!=w37+4; ss+=1) *rr++ = *ss;
  /* #222: (@35[:8:4;2:4] = @33) */
  for (rr=w35+0, ss=w33; rr!=w35+8; rr+=4) for (tt=rr+2; tt!=rr+4; tt+=1) *tt = *ss++;
  /* #223: @33 = @37[:4] */
  for (rr=w33, ss=w37+0; ss!=w37+4; ss+=1) *rr++ = *ss;
  /* #224: (@35[1:9:2] = @33) */
  for (rr=w35+1, ss=w33; rr!=w35+9; rr+=2) *rr = *ss++;
  /* #225: @39 = @35' */
  casadi_trans(w35,casadi_s9, w39, casadi_s9, iw);
  /* #226: output[2][0] = @39 */
  casadi_copy(w39, 9, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s5;
    case 2: return casadi_s11;
    case 3: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s9;
    case 3: return casadi_s11;
    case 4: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 117;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
